### ISSUE TITLE
Support @observes (or and a similar annotation)

### ISSUE THREAD

**Issue by bmaehr** [NullVoxPopuli/ember-deep-tracked#369]
It would be nice to make @observes working on this deep tracking.

Because there is still no replacement for observer (which was able to react ob changes of the object).

**Comment by NullVoxPopuli** [comment]
observing isn't in the spirit of data derivation, and it seems every ecosystem is migrating away from observers -- they all cause spooky-action-at-a-distance, and have proven hard to debug :cry: 

if you have a specific example of data-flow where you'd like to use an observer, I can try to show you how to rewrite into much easier to debug.

Let's open a new issue for that tho.

**Comment by bmaehr** [comment]
Already this "Data Down, Action Up" thing was a very restricting thing. But if now the Down component is even not able to react on changes of the data how should it work then?

The use case I have is a component B doing things based on complex data provided by the parent. Until now it reacted on the change of this data by the parent component A (or in fact changed by an other child component C of parent A). 

An other possibility would it be to trigger the action on component B by an action on the parent A.

**Comment by NullVoxPopuli** [comment]
> Already this "Data Down, Action Up" thing was a very restricting thing. 

data dawn, actions up, aka "one way data flow" is how all frameworks are converging, because it maximizes debuggability and maintenance.

> But if now the Down component is even not able to react on changes of the data how should it work then?

Observing is not the "down part" the down part is:
- passing data to components
- deriving data from other data

> The use case I have is a component B doing things based on complex data provided by the parent. Until now it reacted on the change of this data by the parent component A (or in fact changed by an other child component C of parent A).

Is this all automated? no use interactions whatsoever?

> An other possibility would it be to trigger the action on component B by an action on the parent A.

Can you write out what you mean? or, better yet, create a demo here: 

https://limber.glimdown.com/edit?c=JYWwDg9gTgLgBAYQuCA7Apq%2BAzKy4DkAAgOYA2oI6UA9AMbKQZYEDcAUKJLHAN5wwoAQzoBrdABM4AXzi58xcpWo1BI0cFQk2nFD35oZcvCEJF0IAEYqQECcGzBqO9uzpkhAZ0%2BI46AB4wmBI%2BSCjM8LzscHAAPEHgHkEAfNExvmmxqhZgSeip0q7uXj4AQn6BwaGMaJiRmQm5QilpMeWu6XEIcDSpMVmNeQWuAdzwEujYQgCuZPDF3nAAEuhkZBAA6tBkUgFBqCGINRF8aURqYpJwDNNYcAC8cAAMHGmadFAWdQ9wABQAlA9kgIABbATwAOhudwA1I8AIyvfqDZr5VpxMDJACaEGmcBBQgAbuhrhRLlIYCCSZZpjAYIZeLxKeCobisNJZDBQOhIVlMR10rEaXSGbxDAAidzAMTi0Es96fKjs6TJBBk0RZYX01B9QWWKC6mLo2LlXqZbKJVHDIA&format=gjs

**Comment by bmaehr** [comment]
> > Already this "Data Down, Action Up" thing was a very restricting thing.
> 
> data dawn, actions up, aka "one way data flow" is how all frameworks are converging, because it maximizes debuggability and maintability.

In most cases it useful (because of the mentioned reasons) to let the data flow only in one direction. But the framework should not enforce it (or at least have possibilities to make it different for cases it is other way round better)

> > But if now the Down component is even not able to react on changes of the data how should it work then?
> 
> Observing is not the "down part" the down part is:
> 
> * passing data to components
> * deriving data from other data

"Observing" is part of the "deriving data from other data" because if you think further than the stupid playground examples you might make more complex actions requiring for example rest calls for deriving data

> > The use case I have is a component B doing things based on complex data provided by the parent. Until now it reacted on the change of this data by the parent component A (or in fact changed by an other child component C of parent A).
> 
> Is this all automated? no use interactions whatsoever?

User Interactions happens in most cases in component C, could be also from parent component A and some actions on component B.

> > An other possibility would it be to trigger the action on component B by an action on the parent A.
> 
> Can you write out what you mean? 

A user action on parent component A triggers a java script action on parent component A which should trigger an action on child component B.

**Comment by NullVoxPopuli** [comment]
> "Observing" is part of the "deriving data from other data" because if you think further than the stupid playground examples you might make more complex actions requiring for example rest calls for deriving data

you don't need an observer to fetch data, you can do it in a getter - like a cached getter, with instrumented promise, like in these examples:
- https://github.com/tracked-tools/ember-async-data
- https://reactive.nullvoxpopuli.com/functions/remote_data.RemoteData-1.html
- or doing it yourself:
  ```js
  @cached 
  get request() {
    let state = new TrackedObject({ isLoading: true, value: null, error: null });
    
    fetch('..')
      .then(result => result.json())
      .then(json => state.value = json)
      .catch(error => state.error = error)
      .finally(() => state.isLoading = false);
    
    return state;
  }
  ```
  (this is basically, once you strip away edge case handling, reactivity, and fault tolerance, what the libraries are doing)

> A user action on parent component A triggers a java script action on parent component A which should trigger an action on child component B.

based on what you're describing, I'm still not sure what you're trying to do, or how observers are even involved.

Can you please create a reproduction of your situation in this REPL / Playground, so that I can help further? thank you!!!


https://limber.glimdown.com/edit?c=JYWwDg9gTgLgBAYQuCA7Apq%2BAzKy4DkAAgOYA2oI6UA9AMbKQZYEDcAUKJLHAN5wwoAQzoBrdABM4AXzi58xcpWo1BI0cFQk2nFD35oZcvCEJF0IAEYqQECcGzBqO9uzpkhAZ0%2BI46AB4wmBI%2BSCjM8LzscHAAPEHgHkEAfNExvmmxqhZgSeip0q7uXj4AQn6BwaGMaJiRmQm5QilpMeWu6XEIcDSpMVmNeQWuAdzwEujYQgCuZPDF3nAAEuhkZBAA6tBkUgFBqCGINRF8aURqYpJwDNNYcAC8cAAMHGmadFAWdQ9wABQAlA9kgIABbATwAOhudwA1I8AIyvfqDZr5VpxMDJACaEGmcBBQgAbuhrhRLlIYCCSZZpjAYIZeLxKeCobisNJZDBQOhIVlMR10rEaXSGbxDAAidzAMTi0Es96fKjs6TJBBk0RZYX01B9QWWKC6mLo2LlXqZbKJVHDIA&format=gjs

**Comment by NullVoxPopuli** [comment]
References:
- https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-observers.md
- https://discuss.emberjs.com/t/why-should-i-not-use-observers-in-my-ember-application/16868/3
